ALTER TABLE "perjadin_document" DROP CONSTRAINT "perjadin_document_other_fields_null_check";--> statement-breakpoint
ALTER TABLE "perjadin_document" DROP CONSTRAINT "perjadin_document_kind_check";--> statement-breakpoint
ALTER TABLE "perjadin_document" DROP CONSTRAINT "perjadin_document_peserta_fields_check";--> statement-breakpoint
ALTER TABLE "perjadin_document_folder" DROP CONSTRAINT "perjadin_document_folder_kind_check";--> statement-breakpoint
ALTER TABLE "perjadin_document" ALTER COLUMN "document_date" DROP NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "perjadin_document_sppd_unique" ON "perjadin_document" USING btree ("perjadin_id","school_id") WHERE "perjadin_document"."kind" = 'SPPD';--> statement-breakpoint
ALTER TABLE "perjadin_document" ADD CONSTRAINT "perjadin_document_day_sheet_fields_check" CHECK ("perjadin_document"."kind" not in ('Daftar Hadir Narasumber', 'Daftar Hadir Pendamping') or ("perjadin_document"."document_date" is not null and "perjadin_document"."school_id" is null and "perjadin_document"."participant_type" is null and "perjadin_document"."starts_at" is null and "perjadin_document"."ends_at" is null));--> statement-breakpoint
ALTER TABLE "perjadin_document" ADD CONSTRAINT "perjadin_document_sppd_fields_check" CHECK ("perjadin_document"."kind" <> 'SPPD' or ("perjadin_document"."school_id" is not null and "perjadin_document"."document_date" is null and "perjadin_document"."participant_type" is null and "perjadin_document"."starts_at" is null and "perjadin_document"."ends_at" is null));--> statement-breakpoint
ALTER TABLE "perjadin_document" ADD CONSTRAINT "perjadin_document_kind_check" CHECK ("perjadin_document"."kind" in ('Daftar Hadir Peserta', 'Daftar Hadir Narasumber', 'Daftar Hadir Pendamping', 'SPPD'));--> statement-breakpoint
ALTER TABLE "perjadin_document" ADD CONSTRAINT "perjadin_document_peserta_fields_check" CHECK ("perjadin_document"."kind" <> 'Daftar Hadir Peserta' or ("perjadin_document"."document_date" is not null and "perjadin_document"."school_id" is not null and "perjadin_document"."participant_type" is not null and "perjadin_document"."starts_at" is not null and "perjadin_document"."ends_at" is not null));--> statement-breakpoint
ALTER TABLE "perjadin_document_folder" ADD CONSTRAINT "perjadin_document_folder_kind_check" CHECK ("perjadin_document_folder"."kind" in ('Daftar Hadir Peserta', 'Daftar Hadir Narasumber', 'Daftar Hadir Pendamping', 'SPPD'));