import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  pgSchema,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Identity. Better Auth's `user` is a sign-in credential; **`person` is the human**,
 * and every domain foreign key in this schema points at `person.id`.
 *
 * The reason is concrete: a Group is assembled when a Perjadin is planned, and a
 * professor may be named to it months before they first sign in. A domain that
 * FKs into `user` cannot express that.
 */

/** Matches `ROLES` in `@sugt/domain`, character for character. */
export const ROLE_VALUES = ["Staff", "Teaching Team"] as const;

/**
 * `person` **is** the invite list. There is no separate invite table: a row here is
 * an invitation, and `active = false` is a revocation that preserves every
 * historical reference to that person.
 *
 * `unique (id, role)` looks pointless beside a primary key on `id`. It is not — it
 * is the target of six composite foreign keys elsewhere in this schema, and it is
 * what lets "the PIC is Staff", "only Teaching Team taught a Stream", "only
 * Teaching Team file Class Records" and "only Staff file Session Records" be
 * declarative constraints instead of triggers. **Do not drop it.**
 *
 * None of the six declares `on update`, so all default to `NO ACTION` — which makes
 * `role` **write-once** once a Person has been used anywhere. A wrong role is
 * corrected by revoking the row and creating a new Person. That needs
 * `person_email_key` to be partial (`where active`), which is decided but not yet
 * migrated — see
 * `docs/adr/0013-people-are-added-in-the-tool-and-their-role-is-write-once.md`.
 */
export const person = pgTable(
  "person",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    fullName: text("full_name").notNull(),
    email: text("email").notNull(),
    role: text("role").notNull(),
    active: boolean("active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check("person_role_check", sql`${t.role} in ('Staff', 'Teaching Team')`),
    // Case-insensitive: the Better Auth sign-in hook looks a Person up by lowered email.
    uniqueIndex("person_email_key").on(sql`lower(${t.email})`),
    unique("person_id_role_key").on(t.id, t.role),
  ],
);

/**
 * Better Auth's four core tables live in their own Postgres schema.
 *
 * `session` is the single most load-bearing word in `CONTEXT.md` — a teaching
 * occasion at one School — so the library does not get to own it in `public`.
 * Supabase's own `auth` schema belongs to GoTrue, hence a new one rather than a
 * shared one.
 *
 * **The tables themselves are generated by the Better Auth CLI and are not declared
 * here.** Declaring them twice would make drizzle-kit and the Better Auth CLI fight
 * over the same DDL. The one column the domain adds — `user.person_id` — is added by
 * a hand-written migration for the same reason; see `migrations/`.
 */
export const betterAuth = pgSchema("better_auth");
