#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — provisioning for issue #19, Phase 1.
# Phase 2 (migrate, seed, founding Staff) waits for #24 and is NOT run here.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

INTERNAL_ENV="apps/internal/.env"
PUBLIC_ENV="apps/public/.env"
DB_ENV="packages/db/.env"

# Non-secret facts to paste back onto issue #19 at the end.
FACTS=()
fact() { FACTS+=("$1"); }

gen() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -base64 32
  else head -c 32 /dev/urandom | base64; fi
}

ENV_FILE="$INTERNAL_ENV"

banner "SUGT — provision the environments (issue #19, Phase 1)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Confirm the domains"
say "Settled by the dev. ADR-0002 contradicted itself — its opening line deployed"
say "to sugt.itb.ac.id, its consequences required a domain DITSAMA controls. The"
say "rule wins and the opening line is the error; the correction is booked on #39."
say ""
PUBLIC_APP_URL="https://sugtitb.com"
BETTER_AUTH_URL="https://internal.sugtitb.com"
note "  Public site   $PUBLIC_APP_URL"
note "  Internal tool $BETTER_AUTH_URL"
say ""
note "Buy sugtitb.com first if you have not — stage 6 attaches both to Vercel."
if confirm "Change either of these?"; then
  ask PUBLIC_APP_URL  "Public site base URL:"
  ask BETTER_AUTH_URL "Internal tool base URL:"
fi
say ""
warn "The internal URL is also what students scan on a QR code at /f/{token}."
note "That was decided in #18: the public app holds no credentials, so it cannot serve it."
INTERNAL_APP_URL="$BETTER_AUTH_URL"
write_env BETTER_AUTH_URL "$BETTER_AUTH_URL"
write_env PUBLIC_APP_URL  "$PUBLIC_APP_URL"
fact "Public app URL: $PUBLIC_APP_URL"
fact "Internal app URL: $BETTER_AUTH_URL"
pause "Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Supabase — the development project"
say "Two projects. This is the one previews and local work both point at, so it"
say "is the one whose credentials land in your local .env files."
open_url "https://supabase.com/dashboard/new"
step "Create the project. Pick a region close to Indonesia (ap-southeast-1)."
step "Project Settings → General: copy the project ref and region."
ask SUPABASE_DEV_REF    "Development project ref:"
ask SUPABASE_DEV_REGION "Development region:"
ask SUPABASE_DEV_TIER   "Plan tier (free / pro):"
say ""
step "Project Settings → Database → Connection string."
warn "Two strings, and they are NOT interchangeable."
note "  DATABASE_URL — Transaction pooler, port 6543 — the apps at runtime"
note "  DIRECT_URL   — Session pooler,     port 5432 — drizzle-kit migrations"
ask_secret DATABASE_URL "Paste the TRANSACTION pooler string (port 6543):"
ask_secret DIRECT_URL   "Paste the SESSION pooler string (port 5432):"
say ""
step "Project Settings → API: copy the Project URL and the service_role key."
warn "service_role bypasses RLS. It never leaves @sugt/internal and is never NEXT_PUBLIC_*."
ask       SUPABASE_URL              "Project URL:"
ask_secret SUPABASE_SERVICE_ROLE_KEY "service_role key:"
write_env DATABASE_URL              "$DATABASE_URL"
write_env DIRECT_URL                "$DIRECT_URL"
write_env SUPABASE_URL              "$SUPABASE_URL"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
fact "Supabase dev: ref $SUPABASE_DEV_REF, region $SUPABASE_DEV_REGION, tier $SUPABASE_DEV_TIER"
pause "Press Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Supabase — the production project"
say "Create it now; its credentials go straight into Vercel in stage 6 and are"
say "deliberately NOT written to any local file."
open_url "https://supabase.com/dashboard/new"
step "Create a second project. Same region."
step "Project Settings → General: copy the ref and region."
ask SUPABASE_PROD_REF    "Production project ref:"
ask SUPABASE_PROD_REGION "Production region:"
ask SUPABASE_PROD_TIER   "Plan tier (free / pro):"
note "Keep this tab open — stage 6 needs its connection strings and service_role key."
fact "Supabase prod: ref $SUPABASE_PROD_REF, region $SUPABASE_PROD_REGION, tier $SUPABASE_PROD_TIER"
pause "Press Enter to continue."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Buckets — on BOTH projects"
say "Two buckets each, and the visibility split is doing real work."
open_url "https://supabase.com/dashboard/project/$SUPABASE_DEV_REF/storage/buckets"
step "Create 'receipts'      — PRIVATE. Transaction evidence."
step "Create 'public-media'  — PUBLIC.  Published Story photographs."
say ""
warn "Add NO bucket policies to either. Zero is correct, not an omission:"
note "every access goes through the service role, which is never subject to RLS (#8)."
note "A receipt is reached by a signed URL the internal app mints after checking Staff."
say ""
step "Now repeat both buckets on the PRODUCTION project."
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROD_REF/storage/buckets"
pause "Both buckets created on both projects? Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Google OAuth — the development client"
say "Google is the only sign-in provider. Email-and-password stays off."
open_url "https://console.cloud.google.com/apis/credentials"
step "Create Credentials → OAuth client ID → Web application."
step "Authorised redirect URIs — add BOTH of these:"
note "  http://localhost:3001/api/auth/callback/google"
note "  $BETTER_AUTH_URL/api/auth/callback/google"
warn "The path is fixed by Better Auth's mounted handler. A typo here is the"
note "commonest cause of a sign-in loop, and it fails silently at the callback."
ask       GOOGLE_CLIENT_ID     "Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Client secret:"
write_env GOOGLE_CLIENT_ID     "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
say ""
note "Create a SECOND client for production later, or add the production redirect"
note "URI to this one. Either works; separate clients fail more safely."
pause "Press Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Vercel — two projects, and the production variables"
say "One project per app. This is where the production Supabase credentials go."
open_url "https://vercel.com/new"
step "Import this repo twice. Root directory apps/internal, then apps/public."
step "Attach the two domains you settled in stage 1."
say ""
say "On the INTERNAL project → Settings → Environment Variables, set:"
note "  DATABASE_URL, DIRECT_URL          — production, from the tab in stage 3"
note "  SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY"
note "  BETTER_AUTH_SECRET, BETTER_AUTH_URL, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET"
note "  PUBLIC_APP_URL, AGGREGATES_SECRET, REVALIDATE_SECRET"
say ""
say "On the PUBLIC project, set only:"
note "  INTERNAL_APP_URL, AGGREGATES_SECRET, REVALIDATE_SECRET"
say ""
warn "@sugt/public gets NO database variable of any kind. AGENTS.md rule 1."
warn "None of these is NEXT_PUBLIC_* and none may become one — AGGREGATES_SECRET"
note "is the only thing keeping the aggregates endpoints non-browser-reachable."
note "Stage 7 generates the three secrets; come back and paste them if you like."
pause "Press Enter to continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Generate the three shared secrets"
say "Generated here rather than typed, once per environment."
BETTER_AUTH_SECRET=$(gen)
AGGREGATES_SECRET=$(gen)
REVALIDATE_SECRET=$(gen)
write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
write_env AGGREGATES_SECRET  "$AGGREGATES_SECRET"
write_env REVALIDATE_SECRET  "$REVALIDATE_SECRET"
say ""
warn "AGGREGATES_SECRET and REVALIDATE_SECRET are shared between the two apps,"
note "so each is declared on BOTH sides. When you rotate one later, set the new"
note "value on the READER first and the WRITER second — a mismatch fails at"
note "request time rather than build time, which is the harder failure to read."
say ""
note "Values are in $INTERNAL_ENV. Copy them into Vercel when you set stage 6."
pause "Press Enter to continue."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Write the remaining env files"
say "Three files: the internal app, the public app, and @sugt/db."

ENV_FILE="$PUBLIC_ENV"
write_env INTERNAL_APP_URL  "$INTERNAL_APP_URL"
write_env AGGREGATES_SECRET "$AGGREGATES_SECRET"
write_env REVALIDATE_SECRET "$REVALIDATE_SECRET"

ENV_FILE="$DB_ENV"
write_env DATABASE_URL "$DATABASE_URL"
write_env DIRECT_URL   "$DIRECT_URL"
note "drizzle-kit reads DIRECT_URL from packages/db/.env — that is why this file exists."

# finish() reports against whatever ENV_FILE last pointed at. Three files were
# written, so give it a label that says so rather than naming only the last.
ENV_FILE="apps/internal/.env, apps/public/.env and packages/db/.env"
say ""
warn "db:seed runs psql and does NOT read that file. Export it first:"
note "  set -a; source packages/db/.env; set +a"
say ""
warn "turbo.json currently declares only DATABASE_URL. Under envMode: strict an"
note "undeclared variable is invisible to the task even when your shell has it."
note "Add each variable to build, typecheck and dev for the app that reads it."
note "That edit is part of #24's work, not yours."
pause "Press Enter for the summary."

_clear
printf '\n%s%s  What went where%s\n\n' "$BOLD" "$BLUE" "$RESET"
note "  apps/internal/.env  — DATABASE_URL DIRECT_URL SUPABASE_URL"
note "                        SUPABASE_SERVICE_ROLE_KEY BETTER_AUTH_SECRET"
note "                        BETTER_AUTH_URL GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET"
note "                        PUBLIC_APP_URL AGGREGATES_SECRET REVALIDATE_SECRET"
note "  apps/public/.env    — INTERNAL_APP_URL AGGREGATES_SECRET REVALIDATE_SECRET"
note "  packages/db/.env    — DATABASE_URL DIRECT_URL"
printf '\n'
note "  All three are covered by .gitignore's .env* rule. Keep it that way."
printf '\n'
pause "Press Enter."

_clear
printf '\n%s%s  Facts to post on issue #19%s\n\n' "$BOLD" "$BLUE" "$RESET"
for f in "${FACTS[@]}"; do note "  $f"; done
printf '\n'
warn "Post the facts above, never the secrets."
printf '\n%s%s  Phase 2 — NOT NOW%s\n\n' "$BOLD" "$YELLOW" "$RESET"
note "  Do not run db:migrate yet. The current migration set cannot apply from"
note "  empty: 0002 references better_auth.\"user\", a table nothing in this repo"
note "  creates, and its guard names a Better Auth CLI migration that cannot exist."
note "  #24 deletes and regenerates it. Migrate, seed and insert founding Staff"
note "  after #24 lands — in that order."
printf '\n'
pause "Press Enter for the file summary."

finish
